import { timeZonesNames } from '@vvo/tzdb'
import fs from 'node:fs/promises'

console.log(timeZonesNames)

const arrayRows = timeZonesNames.map((name) => `\t'${name}',`).join('\n')

const fileContents = [
	"// Generated by 'scripts/update-time-zones.ts'",
	'',
	'export const TIME_ZONES = [',
	arrayRows,
	'] as const',
	'',
	'export type TimeZone = (typeof TIME_ZONES)[number]',
	'',
]

const destination = 'src/lib/utilities/time-zone.ts'

console.log(`Writing time zone type to ${destination}...`)
await fs.writeFile(destination, fileContents.join('\n'))
