import { timeZonesNames } from '@vvo/tzdb'
import fs from 'node:fs/promises'

console.log(timeZonesNames)

// Add 'UTC' since it's a valid IANA timezone returned by
// Intl.DateTimeFormat().resolvedOptions().timeZone on many Linux systems
// but not included in @vvo/tzdb
const allTimeZones = [...timeZonesNames, 'UTC'].toSorted()

const arrayRows = allTimeZones.map((name) => `\t'${name}',`).join('\n')

const fileContents = [
	"// Generated by 'scripts/update-time-zones.ts'",
	'',
	'export const TIME_ZONES = [',
	arrayRows,
	'] as const',
	'',
	'export type TimeZone = (typeof TIME_ZONES)[number]',
	'',
]

const destination = 'src/lib/utilities/time-zone.ts'

console.log(`Writing time zone type to ${destination}...`)
await fs.writeFile(destination, fileContents.join('\n'))
